<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net462</TargetFrameworks>
    <Version>4.0.0</Version>
    <Description>
C#/.NET library that integrates Atata with MSTest.

Atata.MSTest on GitHub: https://github.com/atata-framework/atata-mstest
Atata Framework documentation: https://atata.io/
      
The package targets .NET 8.0 and .NET Framework 4.6.2.
    </Description>
    <RepositoryUrl>https://github.com/atata-framework/atata-mstest</RepositoryUrl>
    <PackageId>Atata.MSTest</PackageId>
    <PackageTags>atata automation testing test mstest</PackageTags>
    <PackageReleaseNotes>Changelog: https://github.com/atata-framework/atata-mstest/blob/main/CHANGELOG.md</PackageReleaseNotes>
    <PackageProjectUrl>https://github.com/atata-framework/atata-mstest</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Atata" Version="4.0.0" />
    <PackageReference Include="MSTest.TestFramework" Version="4.4.0" />
    <PackageReference Include="PolySharp" Version="1.16.0" PrivateAssets="all" />
  </ItemGroup>

</Project>
